post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhldGEzIiwiaWQiOiI2YTI0ODQ1MjQ3MTE0NDA1MDZhMTc2NGQiLCJpYXQiOjE3ODA3NzgwNzMsImV4cCI6MTc4MDc4MTY3M30.pLZvUDKHfhZqrGQC2-KOaCnL21HUwK_gmZcqoJnrLiM
 
{
  "title": "blogi1",
  "author": "kirjoittaja1",
  "url": "blogi1.fi",
  "likes": 1

}